FROM php:fpm-alpine3.9

#MAINTAINER zhangtongchuan <tongchuanxing@163.com>

#WORKDIR /var/www/html

#CMD ["php-fpm"]



# docker build -t php:nginx .

# docker run --name  myphp -v /git.yonyou.com/docker/php/www:/www  -d php:nginx

# docker run -p 9000:80 --name nginxphp --network testnet -v /git.yonyou.com/docker/php/www:/usr/share/nginx/html -v /git.yonyou.com/docker/php/log/:/var/log/nginx/ -v /git.yonyou.com/docker/php/conf/default.conf:/etc/nginx/conf.d/default.conf -v /git.yonyou.com/docker/php/conf/nginx.conf:/etc/nginx/nginx.conf --link myphp:nginx -d nginx:html